CREATE TABLE [dbo].[Checkout_log_Staging] (

	[tenant_id] varchar(8000) NULL, 
	[equipment_id] varchar(8000) NULL, 
	[checkout_type_id] varchar(8000) NULL, 
	[tenant_user_id] varchar(8000) NULL, 
	[tenant_user_name] varchar(8000) NULL, 
	[checked_in_user_name] varchar(8000) NULL, 
	[date_of_check_in] datetime2(6) NULL, 
	[date_created] datetime2(6) NULL, 
	[created_by_name] varchar(8000) NULL, 
	[date_last_updated] datetime2(6) NULL, 
	[lastupdated_by_name] varchar(8000) NULL, 
	[check_in_condition_id] varchar(8000) NULL, 
	[check_out_condition_id] varchar(8000) NULL, 
	[checkout_comment] varchar(8000) NULL, 
	[checkin_comment] varchar(8000) NULL, 
	[duration] int NULL, 
	[duration_unit] varchar(8000) NULL, 
	[date_estimated_checkin] date NULL, 
	[reference_identifier] varchar(8000) NULL, 
	[reference_id] varchar(8000) NULL, 
	[reference_type] varchar(8000) NULL, 
	[resource_id] varchar(8000) NULL, 
	[about_path] varchar(8000) NULL, 
	[assigned_by_tenant_user_id] varchar(8000) NULL, 
	[assigned_by_tenant_user_name] varchar(8000) NULL, 
	[document_upload_policy_id] varchar(8000) NULL, 
	[equipment_movement_id] varchar(8000) NULL
);