CREATE TABLE [dbo].[Equipment_Calibration_Staging] (

	[id] varchar(8000) NULL, 
	[tenant_id] varchar(8000) NULL, 
	[equipment_id] varchar(8000) NULL, 
	[calibration_date] datetime2(6) NULL, 
	[calibration_result] varchar(8000) NULL, 
	[date_created] datetime2(6) NULL, 
	[created_by_name] varchar(8000) NULL, 
	[date_last_updated] datetime2(6) NULL, 
	[lastupdated_by_name] varchar(8000) NULL, 
	[notes] varchar(8000) NULL, 
	[date_sent_for_calibration] datetime2(6) NULL, 
	[date_service_due] datetime2(6) NULL, 
	[date_service_completed] datetime2(6) NULL, 
	[date_service_canceled] datetime2(6) NULL, 
	[about_path] varchar(8000) NULL, 
	[service_type_id] varchar(8000) NULL, 
	[service_result_id] varchar(8000) NULL, 
	[currency_iso_code] varchar(8000) NULL, 
	[service_fee] decimal(38,6) NULL, 
	[invoice_number] varchar(8000) NULL, 
	[status_code] varchar(8000) NULL, 
	[in_trash] int NULL, 
	[maintenance_schedule_id] varchar(8000) NULL, 
	[service_vendor_id] varchar(8000) NULL, 
	[software_version] varchar(8000) NULL, 
	[service_vendor_address_instance_id] varchar(8000) NULL, 
	[vendor_display_name] varchar(8000) NULL, 
	[vendor_address] varchar(8000) NULL, 
	[compliance_status] varchar(8000) NULL, 
	[document_upload_policy_id] varchar(8000) NULL
);