[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Calibration_Category_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "id", DestinationColumnName = "id"], [SourceColumnName = "tenant_id", DestinationColumnName = "tenant_id"], [SourceColumnName = "name_text", DestinationColumnName = "name_text"], [SourceColumnName = "business_code", DestinationColumnName = "business_code"], [SourceColumnName = "description", DestinationColumnName = "description"], [SourceColumnName = "status", DestinationColumnName = "status"], [SourceColumnName = "date_created", DestinationColumnName = "date_created"], [SourceColumnName = "created_by_name", DestinationColumnName = "created_by_name"], [SourceColumnName = "date_last_updated", DestinationColumnName = "date_last_updated"], [SourceColumnName = "lastupdated_by_name", DestinationColumnName = "lastupdated_by_name"], [SourceColumnName = "calibration_source", DestinationColumnName = "calibration_source"], [SourceColumnName = "calibration_frequency", DestinationColumnName = "calibration_frequency"], [SourceColumnName = "verify_before_use", DestinationColumnName = "verify_before_use"], [SourceColumnName = "max_calibration_interval", DestinationColumnName = "max_calibration_interval"], [SourceColumnName = "calibration_service_type_id", DestinationColumnName = "calibration_service_type_id"], [SourceColumnName = "requires_calibration", DestinationColumnName = "requires_calibration"], [SourceColumnName = "placeholder_template_group_id", DestinationColumnName = "placeholder_template_group_id"], [SourceColumnName = "label_text", DestinationColumnName = "label_text"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared Calibration_Category = let
  Source = PostgreSQL.Database("localhost", "gbs-trutesta-sandbox-prod"),
  #"Navigation 1" = Source{[Schema = "trutesta_equipment", Item = "calibration_category"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"trutesta_equipment.equipment", "trutesta_equipment.print_label_calibration_category_instance", "trutesta_equipment.service_type(calibration_service_type_id)", "trutesta_equipment.service_type(id)"})
in
  #"Removed columns";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Equipment_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "id", DestinationColumnName = "id"], [SourceColumnName = "tenant_id", DestinationColumnName = "tenant_id"], [SourceColumnName = "equipment_type_id", DestinationColumnName = "equipment_type_id"], [SourceColumnName = "equipment_location_id", DestinationColumnName = "equipment_location_id"], [SourceColumnName = "resource_id", DestinationColumnName = "resource_id"], [SourceColumnName = "name_text", DestinationColumnName = "name_text"], [SourceColumnName = "description", DestinationColumnName = "description"], [SourceColumnName = "status", DestinationColumnName = "status"], [SourceColumnName = "manufacturer_name", DestinationColumnName = "manufacturer_name"], [SourceColumnName = "model_no", DestinationColumnName = "model_no"], [SourceColumnName = "serial_no", DestinationColumnName = "serial_no"], [SourceColumnName = "date_created", DestinationColumnName = "date_created"], [SourceColumnName = "created_by_name", DestinationColumnName = "created_by_name"], [SourceColumnName = "date_last_updated", DestinationColumnName = "date_last_updated"], [SourceColumnName = "lastupdated_by_name", DestinationColumnName = "lastupdated_by_name"], [SourceColumnName = "about_path", DestinationColumnName = "about_path"], [SourceColumnName = "organization_id", DestinationColumnName = "organization_id"], [SourceColumnName = "date_active", DestinationColumnName = "date_active"], [SourceColumnName = "date_retired", DestinationColumnName = "date_retired"], [SourceColumnName = "date_offline", DestinationColumnName = "date_offline"], [SourceColumnName = "in_trash", DestinationColumnName = "in_trash"], [SourceColumnName = "service_alert_message", DestinationColumnName = "service_alert_message"], [SourceColumnName = "current_usage", DestinationColumnName = "current_usage"], [SourceColumnName = "status_code", DestinationColumnName = "status_code"], [SourceColumnName = "auto_recommend_maintenance", DestinationColumnName = "auto_recommend_maintenance"], [SourceColumnName = "asset_tag", DestinationColumnName = "asset_tag"], [SourceColumnName = "equipment_load_job_id", DestinationColumnName = "equipment_load_job_id"], [SourceColumnName = "no_of_equipment", DestinationColumnName = "no_of_equipment"], [SourceColumnName = "equipment_key", DestinationColumnName = "equipment_key"], [SourceColumnName = "verify_before_use", DestinationColumnName = "verify_before_use"], [SourceColumnName = "maintenance_schedule_state", DestinationColumnName = "maintenance_schedule_state"], [SourceColumnName = "calibration_category_id", DestinationColumnName = "calibration_category_id"], [SourceColumnName = "is_externally_managed", DestinationColumnName = "is_externally_managed"], [SourceColumnName = "external_key", DestinationColumnName = "external_key"], [SourceColumnName = "requires_scan", DestinationColumnName = "requires_scan"], [SourceColumnName = "available_timesheet", DestinationColumnName = "available_timesheet"], [SourceColumnName = "equipment_checkout_log_id", DestinationColumnName = "equipment_checkout_log_id"], [SourceColumnName = "date_of_purchase", DestinationColumnName = "date_of_purchase"], [SourceColumnName = "equipment_activation_rule_id", DestinationColumnName = "equipment_activation_rule_id"], [SourceColumnName = "equipment_checkout_rule_id", DestinationColumnName = "equipment_checkout_rule_id"], [SourceColumnName = "equipment_checkin_rule_id", DestinationColumnName = "equipment_checkin_rule_id"], [SourceColumnName = "equipment_calibration_rule_id", DestinationColumnName = "equipment_calibration_rule_id"], [SourceColumnName = "site_share", DestinationColumnName = "site_share"], [SourceColumnName = "site_id", DestinationColumnName = "site_id"], [SourceColumnName = "document_placeholder_template_group_id", DestinationColumnName = "document_placeholder_template_group_id"], [SourceColumnName = "track_software_versions", DestinationColumnName = "track_software_versions"], [SourceColumnName = "software_version", DestinationColumnName = "software_version"], [SourceColumnName = "date_last_service", DestinationColumnName = "date_last_service"], [SourceColumnName = "date_service_due", DestinationColumnName = "date_service_due"], [SourceColumnName = "site_equipment_key", DestinationColumnName = "site_equipment_key"], [SourceColumnName = "ext_equipment_key", DestinationColumnName = "ext_equipment_key"], [SourceColumnName = "equipment_piece_type", DestinationColumnName = "equipment_piece_type"], [SourceColumnName = "parent_equipment_id", DestinationColumnName = "parent_equipment_id"], [SourceColumnName = "department_id", DestinationColumnName = "department_id"], [SourceColumnName = "transfer_site_id", DestinationColumnName = "transfer_site_id"], [SourceColumnName = "transfer_type", DestinationColumnName = "transfer_type"], [SourceColumnName = "sub_status_code", DestinationColumnName = "sub_status_code"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared Equipment = let
  Source = PostgreSQL.Database("localhost", "gbs-trutesta-sandbox-prod"),
  #"Navigation 1" = Source{[Schema = "trutesta_equipment", Item = "equipment"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"trutesta_equipment.calibration_category", "trutesta_equipment.digital_asset", "trutesta_equipment.equipment(id)", "trutesta_equipment.equipment(parent_equipment_id)", "trutesta_equipment.equipment_alert", "trutesta_equipment.equipment_asset_tag", "trutesta_equipment.equipment_attribute", "trutesta_equipment.equipment_audit", "trutesta_equipment.equipment_calibration", "trutesta_equipment.equipment_calibration_scope", "trutesta_equipment.equipment_calibration_standard", "trutesta_equipment.equipment_checkout_log(equipment_checkout_log_id)", "trutesta_equipment.equipment_checkout_log(id)", "trutesta_equipment.equipment_form_instance", "trutesta_equipment.equipment_load_job", "trutesta_equipment.equipment_location(department_id)", "trutesta_equipment.equipment_location(equipment_location_id)", "trutesta_equipment.equipment_log", "trutesta_equipment.equipment_movement", "trutesta_equipment.equipment_notification_instance", "trutesta_equipment.equipment_organization", "trutesta_equipment.equipment_service_vendor", "trutesta_equipment.equipment_source", "trutesta_equipment.equipment_tag_instance", "trutesta_equipment.equipment_team", "trutesta_equipment.equipment_type", "trutesta_equipment.inspection", "trutesta_equipment.maintenance_schedule"})
in
  #"Removed columns";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Equipment_Calibration_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "id", DestinationColumnName = "id"], [SourceColumnName = "tenant_id", DestinationColumnName = "tenant_id"], [SourceColumnName = "equipment_id", DestinationColumnName = "equipment_id"], [SourceColumnName = "calibration_date", DestinationColumnName = "calibration_date"], [SourceColumnName = "calibration_result", DestinationColumnName = "calibration_result"], [SourceColumnName = "date_created", DestinationColumnName = "date_created"], [SourceColumnName = "created_by_name", DestinationColumnName = "created_by_name"], [SourceColumnName = "date_last_updated", DestinationColumnName = "date_last_updated"], [SourceColumnName = "lastupdated_by_name", DestinationColumnName = "lastupdated_by_name"], [SourceColumnName = "notes", DestinationColumnName = "notes"], [SourceColumnName = "date_sent_for_calibration", DestinationColumnName = "date_sent_for_calibration"], [SourceColumnName = "date_service_due", DestinationColumnName = "date_service_due"], [SourceColumnName = "date_service_completed", DestinationColumnName = "date_service_completed"], [SourceColumnName = "date_service_canceled", DestinationColumnName = "date_service_canceled"], [SourceColumnName = "about_path", DestinationColumnName = "about_path"], [SourceColumnName = "service_type_id", DestinationColumnName = "service_type_id"], [SourceColumnName = "service_result_id", DestinationColumnName = "service_result_id"], [SourceColumnName = "currency_iso_code", DestinationColumnName = "currency_iso_code"], [SourceColumnName = "service_fee", DestinationColumnName = "service_fee"], [SourceColumnName = "invoice_number", DestinationColumnName = "invoice_number"], [SourceColumnName = "status_code", DestinationColumnName = "status_code"], [SourceColumnName = "in_trash", DestinationColumnName = "in_trash"], [SourceColumnName = "maintenance_schedule_id", DestinationColumnName = "maintenance_schedule_id"], [SourceColumnName = "service_vendor_id", DestinationColumnName = "service_vendor_id"], [SourceColumnName = "software_version", DestinationColumnName = "software_version"], [SourceColumnName = "service_vendor_address_instance_id", DestinationColumnName = "service_vendor_address_instance_id"], [SourceColumnName = "vendor_display_name", DestinationColumnName = "vendor_display_name"], [SourceColumnName = "vendor_address", DestinationColumnName = "vendor_address"], [SourceColumnName = "compliance_status", DestinationColumnName = "compliance_status"], [SourceColumnName = "document_upload_policy_id", DestinationColumnName = "document_upload_policy_id"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared Equipment_Calibration = let
  Source = PostgreSQL.Database("localhost", "gbs-trutesta-sandbox-prod"),
  #"Navigation 1" = Source{[Schema = "trutesta_equipment", Item = "equipment_calibration"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"trutesta_equipment.equipment", "trutesta_equipment.equipment_audit", "trutesta_equipment.equipment_log", "trutesta_equipment.maintenance_schedule", "trutesta_equipment.service_result", "trutesta_equipment.service_type", "trutesta_equipment.service_vendor", "trutesta_equipment.service_vendor_address_instance"})
in
  #"Removed columns";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Checkout_log_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "tenant_id", DestinationColumnName = "tenant_id"], [SourceColumnName = "equipment_id", DestinationColumnName = "equipment_id"], [SourceColumnName = "checkout_type_id", DestinationColumnName = "checkout_type_id"], [SourceColumnName = "tenant_user_id", DestinationColumnName = "tenant_user_id"], [SourceColumnName = "tenant_user_name", DestinationColumnName = "tenant_user_name"], [SourceColumnName = "checked_in_user_name", DestinationColumnName = "checked_in_user_name"], [SourceColumnName = "date_of_check_in", DestinationColumnName = "date_of_check_in"], [SourceColumnName = "date_created", DestinationColumnName = "date_created"], [SourceColumnName = "created_by_name", DestinationColumnName = "created_by_name"], [SourceColumnName = "date_last_updated", DestinationColumnName = "date_last_updated"], [SourceColumnName = "lastupdated_by_name", DestinationColumnName = "lastupdated_by_name"], [SourceColumnName = "check_in_condition_id", DestinationColumnName = "check_in_condition_id"], [SourceColumnName = "check_out_condition_id", DestinationColumnName = "check_out_condition_id"], [SourceColumnName = "checkout_comment", DestinationColumnName = "checkout_comment"], [SourceColumnName = "checkin_comment", DestinationColumnName = "checkin_comment"], [SourceColumnName = "duration", DestinationColumnName = "duration"], [SourceColumnName = "duration_unit", DestinationColumnName = "duration_unit"], [SourceColumnName = "date_estimated_checkin", DestinationColumnName = "date_estimated_checkin"], [SourceColumnName = "reference_identifier", DestinationColumnName = "reference_identifier"], [SourceColumnName = "reference_id", DestinationColumnName = "reference_id"], [SourceColumnName = "reference_type", DestinationColumnName = "reference_type"], [SourceColumnName = "resource_id", DestinationColumnName = "resource_id"], [SourceColumnName = "about_path", DestinationColumnName = "about_path"], [SourceColumnName = "assigned_by_tenant_user_id", DestinationColumnName = "assigned_by_tenant_user_id"], [SourceColumnName = "assigned_by_tenant_user_name", DestinationColumnName = "assigned_by_tenant_user_name"], [SourceColumnName = "document_upload_policy_id", DestinationColumnName = "document_upload_policy_id"], [SourceColumnName = "equipment_movement_id", DestinationColumnName = "equipment_movement_id"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared Checkout_log = let
  Source = PostgreSQL.Database("localhost", "gbs-trutesta-sandbox-prod"),
  #"Navigation 1" = Source{[Schema = "trutesta_equipment", Item = "equipment_checkout_log"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"id", "trutesta_equipment.equipment(equipment_id)", "trutesta_equipment.equipment(id)", "trutesta_equipment.equipment_checkout_type", "trutesta_equipment.equipment_condition(check_in_condition_id)", "trutesta_equipment.equipment_condition(check_out_condition_id)", "trutesta_equipment.equipment_movement"})
in
  #"Removed columns";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Checkout_Type_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "id", DestinationColumnName = "id"], [SourceColumnName = "tenant_id", DestinationColumnName = "tenant_id"], [SourceColumnName = "name_text", DestinationColumnName = "name_text"], [SourceColumnName = "business_code", DestinationColumnName = "business_code"], [SourceColumnName = "description", DestinationColumnName = "description"], [SourceColumnName = "status", DestinationColumnName = "status"], [SourceColumnName = "checkin_checklist_id", DestinationColumnName = "checkin_checklist_id"], [SourceColumnName = "placeholder_template_group_id", DestinationColumnName = "placeholder_template_group_id"], [SourceColumnName = "date_created", DestinationColumnName = "date_created"], [SourceColumnName = "created_by_name", DestinationColumnName = "created_by_name"], [SourceColumnName = "date_last_updated", DestinationColumnName = "date_last_updated"], [SourceColumnName = "lastupdated_by_name", DestinationColumnName = "lastupdated_by_name"], [SourceColumnName = "document_upload_policy_id", DestinationColumnName = "document_upload_policy_id"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared Checkout_Type = let
  Source = PostgreSQL.Database("localhost", "gbs-trutesta-sandbox-prod"),
  #"Navigation 1" = Source{[Schema = "trutesta_equipment", Item = "equipment_checkout_type"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"trutesta_equipment.equipment_checkout_log"})
in
  #"Removed columns";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Location_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "id", DestinationColumnName = "id"], [SourceColumnName = "tenant_id", DestinationColumnName = "tenant_id"], [SourceColumnName = "name_text", DestinationColumnName = "name_text"], [SourceColumnName = "description", DestinationColumnName = "description"], [SourceColumnName = "status", DestinationColumnName = "status"], [SourceColumnName = "geo_latitude", DestinationColumnName = "geo_latitude"], [SourceColumnName = "geo_longitude", DestinationColumnName = "geo_longitude"], [SourceColumnName = "date_created", DestinationColumnName = "date_created"], [SourceColumnName = "created_by_name", DestinationColumnName = "created_by_name"], [SourceColumnName = "date_last_updated", DestinationColumnName = "date_last_updated"], [SourceColumnName = "lastupdated_by_name", DestinationColumnName = "lastupdated_by_name"], [SourceColumnName = "organization_id", DestinationColumnName = "organization_id"], [SourceColumnName = "equipment_location_type_id", DestinationColumnName = "equipment_location_type_id"], [SourceColumnName = "site_id", DestinationColumnName = "site_id"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared Location = let
  Source = PostgreSQL.Database("localhost", "gbs-trutesta-sandbox-prod"),
  #"Navigation 1" = Source{[Schema = "trutesta_equipment", Item = "equipment_location"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"trutesta_equipment.consumable", "trutesta_equipment.consumable_batch", "trutesta_equipment.equipment(id)", "trutesta_equipment.equipment(id) 2", "trutesta_equipment.equipment_location_tenant_user", "trutesta_equipment.equipment_location_type", "trutesta_equipment.equipment_movement(id)", "trutesta_equipment.equipment_movement(id) 2"})
in
  #"Removed columns";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Maintenance_Schedule_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "id", DestinationColumnName = "id"], [SourceColumnName = "tenant_id", DestinationColumnName = "tenant_id"], [SourceColumnName = "equipment_id", DestinationColumnName = "equipment_id"], [SourceColumnName = "service_type_id", DestinationColumnName = "service_type_id"], [SourceColumnName = "frequency_unit", DestinationColumnName = "frequency_unit"], [SourceColumnName = "frequency", DestinationColumnName = "frequency"], [SourceColumnName = "instructions", DestinationColumnName = "instructions"], [SourceColumnName = "display_order", DestinationColumnName = "display_order"], [SourceColumnName = "date_created", DestinationColumnName = "date_created"], [SourceColumnName = "created_by_name", DestinationColumnName = "created_by_name"], [SourceColumnName = "date_last_updated", DestinationColumnName = "date_last_updated"], [SourceColumnName = "lastupdated_by_name", DestinationColumnName = "lastupdated_by_name"], [SourceColumnName = "is_internal", DestinationColumnName = "is_internal"], [SourceColumnName = "oncomplete_document_upload_policy_id", DestinationColumnName = "oncomplete_document_upload_policy_id"], [SourceColumnName = "date_calculated_service_due", DestinationColumnName = "date_calculated_service_due"], [SourceColumnName = "status_code", DestinationColumnName = "status_code"], [SourceColumnName = "service_vendor_id", DestinationColumnName = "service_vendor_id"], [SourceColumnName = "alert_threshold", DestinationColumnName = "alert_threshold"], [SourceColumnName = "date_calculated_alert", DestinationColumnName = "date_calculated_alert"], [SourceColumnName = "service_vendor_address_instance_id", DestinationColumnName = "service_vendor_address_instance_id"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared Maintenance_Schedule = let
  Source = PostgreSQL.Database("localhost", "gbs-trutesta-sandbox-prod"),
  #"Navigation 1" = Source{[Schema = "trutesta_equipment", Item = "maintenance_schedule"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"trutesta_equipment.equipment", "trutesta_equipment.equipment_calibration", "trutesta_equipment.service_type", "trutesta_equipment.service_vendor", "trutesta_equipment.service_vendor_address_instance"})
in
  #"Removed columns";
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "Service_Type_DataDestination", IsNewTarget = true], Settings = [Kind = "Manual", AllowCreation = true, ColumnSettings = [Mappings = {[SourceColumnName = "id", DestinationColumnName = "id"], [SourceColumnName = "tenant_id", DestinationColumnName = "tenant_id"], [SourceColumnName = "name_text", DestinationColumnName = "name_text"], [SourceColumnName = "description", DestinationColumnName = "description"], [SourceColumnName = "status", DestinationColumnName = "status"], [SourceColumnName = "date_created", DestinationColumnName = "date_created"], [SourceColumnName = "created_by_name", DestinationColumnName = "created_by_name"], [SourceColumnName = "date_last_updated", DestinationColumnName = "date_last_updated"], [SourceColumnName = "lastupdated_by_name", DestinationColumnName = "lastupdated_by_name"], [SourceColumnName = "business_code", DestinationColumnName = "business_code"], [SourceColumnName = "is_type_calibration", DestinationColumnName = "is_type_calibration"], [SourceColumnName = "placeholder_template_group_id", DestinationColumnName = "placeholder_template_group_id"], [SourceColumnName = "checklist_id", DestinationColumnName = "checklist_id"], [SourceColumnName = "is_internal", DestinationColumnName = "is_internal"], [SourceColumnName = "oncomplete_document_upload_policy_id", DestinationColumnName = "oncomplete_document_upload_policy_id"], [SourceColumnName = "calibration_category_id", DestinationColumnName = "calibration_category_id"], [SourceColumnName = "color", DestinationColumnName = "color"], [SourceColumnName = "tag_scheme_id", DestinationColumnName = "tag_scheme_id"], [SourceColumnName = "icon", DestinationColumnName = "icon"]}], DynamicSchema = false, UpdateMethod = [Kind = "Replace"], TypeSettings = [Kind = "Table"]]]}]
shared Service_Type = let
  Source = PostgreSQL.Database("localhost", "gbs-trutesta-sandbox-prod"),
  #"Navigation 1" = Source{[Schema = "trutesta_equipment", Item = "service_type"]}[Data],
  #"Removed columns" = Table.RemoveColumns(#"Navigation 1", {"trutesta_equipment.calibration_category(calibration_category_id)", "trutesta_equipment.calibration_category(id)", "trutesta_equipment.equipment_calibration", "trutesta_equipment.maintenance_schedule"})
in
  #"Removed columns";
shared Calibration_Category_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false, HierarchicalNavigation = true]),
  Navigation_1 = Pattern{[workspaceId = "."]}[Data],
  Navigation_2 = Navigation_1{[displayName = "WarehouseNew"]}[Data],
  Navigation_3 = Navigation_2{[Schema = "dbo"]}[Data],
  TableNavigation = Navigation_3{[Name = "Calibration_Category_Staging"]}?[Data]?
in
  TableNavigation;
shared Equipment_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false, HierarchicalNavigation = true]),
  Navigation_1 = Pattern{[workspaceId = "."]}[Data],
  Navigation_2 = Navigation_1{[displayName = "WarehouseNew"]}[Data],
  Navigation_3 = Navigation_2{[Schema = "dbo"]}[Data],
  TableNavigation = Navigation_3{[Name = "Equipment_Staging"]}?[Data]?
in
  TableNavigation;
shared Service_Type_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false, HierarchicalNavigation = true]),
  Navigation_1 = Pattern{[workspaceId = "."]}[Data],
  Navigation_2 = Navigation_1{[displayName = "WarehouseNew"]}[Data],
  Navigation_3 = Navigation_2{[Schema = "dbo"]}[Data],
  TableNavigation = Navigation_3{[Name = "Service_Type_Staging"]}?[Data]?
in
  TableNavigation;
shared Location_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false, HierarchicalNavigation = true]),
  Navigation_1 = Pattern{[workspaceId = "."]}[Data],
  Navigation_2 = Navigation_1{[displayName = "WarehouseNew"]}[Data],
  Navigation_3 = Navigation_2{[Schema = "dbo"]}[Data],
  TableNavigation = Navigation_3{[Name = "Location_Staging"]}?[Data]?
in
  TableNavigation;
shared Checkout_Type_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false, HierarchicalNavigation = true]),
  Navigation_1 = Pattern{[workspaceId = "."]}[Data],
  Navigation_2 = Navigation_1{[displayName = "WarehouseNew"]}[Data],
  Navigation_3 = Navigation_2{[Schema = "dbo"]}[Data],
  TableNavigation = Navigation_3{[Name = "Checkout_Type_Staging"]}?[Data]?
in
  TableNavigation;
shared Maintenance_Schedule_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false, HierarchicalNavigation = true]),
  Navigation_1 = Pattern{[workspaceId = "."]}[Data],
  Navigation_2 = Navigation_1{[displayName = "WarehouseNew"]}[Data],
  Navigation_3 = Navigation_2{[Schema = "dbo"]}[Data],
  TableNavigation = Navigation_3{[Name = "Maintenance_Schedule_Staging"]}?[Data]?
in
  TableNavigation;
shared Equipment_Calibration_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false, HierarchicalNavigation = true]),
  Navigation_1 = Pattern{[workspaceId = "."]}[Data],
  Navigation_2 = Navigation_1{[displayName = "WarehouseNew"]}[Data],
  Navigation_3 = Navigation_2{[Schema = "dbo"]}[Data],
  TableNavigation = Navigation_3{[Name = "Equipment_Calibration_Staging"]}?[Data]?
in
  TableNavigation;
shared Checkout_log_DataDestination = let
  Pattern = Fabric.Warehouse([CreateNavigationProperties = false, HierarchicalNavigation = true]),
  Navigation_1 = Pattern{[workspaceId = "."]}[Data],
  Navigation_2 = Navigation_1{[displayName = "WarehouseNew"]}[Data],
  Navigation_3 = Navigation_2{[Schema = "dbo"]}[Data],
  TableNavigation = Navigation_3{[Name = "Checkout_log_Staging"]}?[Data]?
in
  TableNavigation;
